### ISSUE TITLE
switchteams.gsc doesn't work properly

### ISSUE THREAD

**Issue by IshKaigen** [Draakoor/h2m-gscscripts#1]
Everytime i execute the !switchteams commands it tells me "You've used all your team switches for this game" even though i have not. I tried to edit the .gsc script to allow a higher number of limits but no matter what i change it keeps telling me I've used up all my team switches.

**Comment by Draakoor** [comment]
You did not read the readme. Thats a client only script! read the readme first before asking or you will get no support in the future!
