### ISSUE TITLE
allowteamselection.gsc has problems with Bots.

### ISSUE THREAD

**Issue by IshKaigen** [Draakoor/h2m-gscscripts#2]
Whenever i use this script, only 10 bots total (5 v 5) on the ally and enemy teams spawn, the rest get stuck in spectator mode. Without the script the lobby fills up with bots like normal. Not sure if this is intentional to allow spots to switch but if it is, there needs to be a way to customize this number let us change how many bots are allowed to play in the match.

**Comment by Draakoor** [comment]
You did not read the readme. Thats a client only script! read the readme first before asking or you will get no support in the future!
